[build]
  functions = "netlify/functions"  
  publish = "public"  

[[redirects]]
  from = "/"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/webmain"
  to = "/.netlify/functions/app"
  status = 200