[build]
  functions = "netlify/functions"  
  publish = "public"  

[[redirects]]
  from = "/"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/main"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/send-email"  
  to = "/.netlify/functions/send-email"
  status = 200